name: Android CI/CD

on:
  push:
    branches: ["*",]

jobs:
  android-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Run Unit Tests
        run: ./gradlew testDebugUnitTest

      - name: Build Debug APK
        run: ./gradlew assembleDebug

      - uses: actions/upload-artifact@v4
        with:
          name: app-debug.apk
          path: app/build/outputs/apk/debug/app-debug.apk

#      - name: Build Release APK
#        run: ./gradlew assembleRelease
#
#      - uses: actions/upload-artifact@v4
#        with:
#          name: app-release-unsigned.apk
#          path: app/build/outputs/apk/release/app-release-unsigned.apk
